### PR TITLE
WIP: bump bundled libzmq to 4.2.2 and enable draft by default

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by sublee** [comment]
I love it!

**Comment by minrk** [comment]
I'll add the extra methods for the draft sockets that need it in a subsequent PR.

**Comment by bluca** [comment]
In CZMQ we have a similar problem, and the solution we use is to have DRAFT flags there too. So if a user enables it, it's at their risk of breakages. And default use cases are not exposed.

**Comment by minrk** [comment]
Closing in favor of #1057, which enables draft support but not by default, and doesn't bump bundled libzmq to 4.2.2, since it doesn't build correctly on Windows.

**Pull request closed without merging**
