### PR TITLE
_AsyncSocket: cancel timers upon success or exception

### PR DESCRIPTION
**Pull request by p4l1ly**
Resolves https://github.com/zeromq/pyzmq/issues/1526

### CODE REVIEW

**Comment by p4l1ly** [comment]
Both tornado's and asyncio's `call_later` returns an object that has the `cancel()` method. For other IOLoop implementations, `_call_later` can be overriden, returning e.g. `_NoTimer`.

**Comment by minrk** [comment]
Thanks for the PR!


Looks like tornado timeouts don't always have cancel:

> AttributeError: '_Timeout' object has no attribute 'cancel'

This is in the "oldest supported tornado" test case, with tornado 4.5. We can bump minimum tornado to 5.x probably for `zmq.eventloop.future`, if that's when they introduced the cancel method. Or we can add an api shim.

**Comment by p4l1ly** [comment]
`ioloop.remove_timeout` works in all versions of tornado, so I've decided to use it for tornado instead of `.cancel` which is compatible with asyncio but not compatible with tornado 4.5.

**Comment by minrk** [comment]
Perfect, thanks!

**Pull request merged**
