### PR TITLE
TEST

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
It looks like per-package repository settings do not transfer (hence the failed runs, they should not run at all). I'll open an issue upstream and disable the hook for now.

**Comment by minrk** [comment]
Should I be able to download packages from the OBS builds? All I see are "no data for..." when I click the download links, e.g. [here](https://build.opensuse.org/package/show/network:messaging:zeromq:git-stable/libzmq)

**Comment by bluca** [comment]
That's weird, looks like the UI is borken ATM, was working last time I checked - anyway, direct link to the repository: https://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/

**Comment by minrk** [comment]
What happens when there's a new build? Do direct links stop working? Is there a permalink for e.g. release-stable libzmq 4.3.4 on debian 9?

**Comment by bluca** [comment]
It's a standard repository, so only the latest builds are stored. The git-[stable|draft] repositories build on every push to the master/main branches. The release-[stable|draft] repositories build on every new release tag pushed.

**Pull request closed without merging**
