### PR TITLE
bump bundled libzmq to 4.0.6

### PR DESCRIPTION
**Pull request by minrk**
and checksum bundled deps on download, partially because libzmq comes over http.

### CODE REVIEW

**Comment by minrk** [comment]
#677 is going to need a bit more work than expected, because 4.1 apparently broke a few things.

**Comment by minrk** [comment]
I'm going to wait for 4.0.7 / 4.1.2, due to bugs in 4.0.6/4.1.1.

**Comment by koobs** [comment]
4.1.2 and 4.0.7 are out:

https://github.com/zeromq/zeromq4-x/pull/124
https://github.com/zeromq/zeromq4-1/pull/40

**Comment by minrk** [comment]
@koobs thanks, I'll try to do a release with 4.1.2 this week.

**Pull request closed without merging**
