### PR TITLE
Run tox tests with python3.4

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by minrk** [comment]
thanks. I don't use tox, so I'll probably remone the tox.ini.

**Comment by ticosax** [comment]
tox is actually quite useful to test things locally.
At the moment I'm trying to merge .travis.yml and tox.ini to remove the burden of double maintenance. If the outcome is ok, I'll make a PR.

**Comment by minrk** [comment]
I hope you aren't planning to make a PR to cause travis to use tox. That would not be desirable.

I think I will still probably remove tox.ini. I don't maintain it, and never will because I don't use it.

**Comment by ticosax** [comment]
I'm actually trying to spot a bug that I can reproduce only with py34. It would be a shame to debug it without tox. I think, it is a useful tool.
But that's your call.

**Pull request merged**
