### PR TITLE
Add Debian and RPM packaging, and a _service file for OBS

### PR DESCRIPTION
**Pull request by bluca**
@minrk in case you haven't seen it yet, we build libzmq/czmq/zyre/malamute/zproject/zproto packages for x86_64/i586/arm7l/arm64/ppc64el/s390x on Debian 7/8/9/unstable Ubuntu 12.04/14.04/16.04/17.04 SUSE SLE12/Leap42/Tumbleweed RHEL 7 Centos 7 Fedora 25/26/Rawhide on the SUSE's Open Build Service:

https://build.opensuse.org/project/show/network:messaging:zeromq:git-stable
https://build.opensuse.org/project/show/network:messaging:zeromq:git-draft

They are automatically built from git on each merge/push to the repositories. So among other things they are always up to date with the latest versions, in sync. Also packages get rebuilt if a dependency changes, eg: merging a PR in libzmq will also rebuild czmq.

I've added the packaging and the _service in this PR, I've already got it to build:

https://build.opensuse.org/package/show/network:messaging:zeromq:git-stable/pyzmq
https://build.opensuse.org/package/show/network:messaging:zeromq:git-draft/pyzmq

As you can imagine the git-draft project builds all the libraries with the DRAFT APIs enabled.

It took a while as a few dependencies were missing in the older distros - RHEL/CENTOS/SLE12 only do python2 for example. Also Ubuntu 12.04 and Debian 7 are just too old (they have python 3.2 only) so I haven't bothered backporting the world.

In case you like this approach I can enable the trigger on this repository, let me know!

### CODE REVIEW

**Comment by minrk** [comment]
Cool! I've no objection, as long as I never have to edit these files :)

**Comment by bluca** [comment]
Thanks!

Don't worry I can maintain the OBS stuff :-)

The versions are updated automagically on OBS, but for users doing manual, local package builds the only thing you might want to update on a release are the version numbers:

https://github.com/zeromq/pyzmq/blob/master/packaging/redhat/python-pyzmq.spec#L38
https://github.com/zeromq/pyzmq/blob/master/packaging/debian/pyzmq.dsc.obs#L5
https://github.com/zeromq/pyzmq/blob/master/packaging/debian/changelog#L1

Can be scripted easily but not templated, as they need to be in place before builds for OBS to work

**Comment by bluca** [comment]
I've set up the hook in https://github.com/zeromq/pyzmq/settings/installations

**Comment by bluca** [comment]
Also in case you want to add a flair on the README.md that points to the repositories here's the snippets:

```
[![OBS draft](https://img.shields.io/badge/OBS%20master-draft-yellow.svg)](http://software.opensuse.org/download.html?project=home%3Azeromq%3Agit-draft&package=pyzmq)
[![OBS stable](https://img.shields.io/badge/OBS%20master-stable-yellow.svg)](http://software.opensuse.org/download.html?project=home%3Azeromq%3Agit-stable&package=pyzmq)
```

I find that pointing Linux users that want the latest version (without any changes) to the pre-built packages makes my life much easier as it skips all the build & dependencies steps. Up to you of course how/if you want to highlight this in the README.

**Pull request merged**
