### PR TITLE
Add support for zmq_curve_public

### PR DESCRIPTION
**Pull request by chrisjbillington**
Add support for [zmq_curve_public](http://api.zeromq.org/4-2:zmq-curve-public), added in zmq 4.2.

### CODE REVIEW

**Comment by chrisjbillington** [comment]
Tested locally on CPython 2.7 and CPython 3.6 with system zmq 4.2.1 with all non-skipped tests passing on 2.7, and no more tests failing on 3.6 than failed without my changes.

**Comment by minrk** [comment]
Looks right, thanks! I'll work on the failures related to the recent tornado 5 release soon.

**Comment by chrisjbillington** [comment]
Excellent, thanks!

**Comment by chrisjbillington** [comment]
`zmq_curve_public` is only available in zeromq 4.2+, might the bundled libzmq version be updated to be compatible with that for the next release?

**Comment by minrk** [comment]
I'll have another go with zeromq 4.2.3. Last time I tried, 4.2.2 didn't build correctly on Windows so I had to wait.

**Comment by minrk** [comment]
Rebased and working fine. Thanks!

**Comment by chrisjbillington** [comment]
You're welcome, thank you!

**Pull request merged**
